# Generated by Django 4.2.7 on 2023-11-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='amount_60_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
