# Generated by Django 4.2.7 on 2023-11-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0002_alter_requisition_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='amount_60_percent',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
